name: Build

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build backend image and push to ECR
      uses: kciter/aws-ecr-action@v3
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: dev/backend
        region: ap-southeast-1
        tags: latest,${{ github.sha }}
        path: ./web-application/backend
        dockerfile: web-application/backend/Dockerfile

    - name: Build frontend image and push to ECR
      uses: kciter/aws-ecr-action@v3
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: dev/frontend
        region: ap-southeast-1
        tags: latest,${{ github.sha }}
        path: ./web-application/frontend
        dockerfile: web-application/frontend/Dockerfile

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install ecs-deploy
      run: |
        python -m pip install --upgrade pip
        pip install ecs-deploy

    - name: Deploy backend to ECS
      run: |
        ecs deploy doc-search backend --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --region ap-southeast-1

    - name: Deploy frontend to ECS
      run: |
        ecs deploy doc-search frontend --access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --region ap-southeast-1
