name: Run tests

on:
  push:
    branches-ignore:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        cd documentdb_to_es_loader
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
